music/urls.py
from django.conf.urls import url

from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # User urls
    url(r'^registration/$', views.register, name='register'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^account/$', views.user_account, name='account'),
    # Data urls
    url(r'^bands/$', views.BandListView.as_view(), name='bands'),
    url(r'^albums/$', views.AlbumListView.as_view(), name='albums'),  # All albums
    url(r'^band/(?P<pk>[0-9]+)/$', views.BandView.as_view(), name='band'),
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumView.as_view(), name='album'),
    url(r'^albums/(?P<pk>[0-9]+)/$', views.AlbumListView.as_view(), name='albums'),  # Albums for precise band
    # liked bands by users
    url(r'^.*addliked/', views.liked_bands, name='liked'),
    url(r'^.*adddisliked/', views.disliked_bands, name='disliked'),
    # liked
    url(r'^liked/', views.liked, name='liked'),
    url(r'^recommendations/', views.recommendations, name='recommendations'),
    # Test search
    url(r'^search/$', views.search_band, name='search'),
    url(r'^bands/search/$', views.search_band, name='search'),
    url(r'^band/[0-9]+/search/$', views.search_band, name='search'),
    url(r'^album/[0-9]+/search/$', views.search_band, name='search'),
]

server/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('music.urls',
                            namespace='music',
                            app_name='music'),
        )
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
import os

from django.contrib.auth.models import User
from django.core.files import File
from django.db import models
from django.utils.safestring import mark_safe


# Rename uploaded file with class attribute name
# from _download_script import download_song


def update_filename(instance, filename):
    path = 'music/' + str.lower(instance.__class__.__name__) + '/'
    format = str(instance) + '.' + filename.split('.')[-1]

    path = os.path.join(path, format)
    return path if os.path.exists(path) else None


class Languages(models.Model):
    name = models.CharField(max_length=15)


class Status(models.Model):
    name = models.CharField(max_length=15)


class Countries(models.Model):
    name = models.CharField(max_length=20)


class Genres(models.Model):
    name = models.CharField(max_length=255, unique=True)

    @classmethod
    def add_genre(cls, genre):
        try:
            cls.objects.create(
                name=genre,
            )
        except:
            pass
            # print(f'Genre {genre} was not added')


class Band(models.Model):
    name = models.CharField(max_length=100, unique=True)
    popularity = models.IntegerField(default=0)
    image = models.ImageField(upload_to=update_filename)
    country = models.ForeignKey(Countries,
                                models.SET_NULL,
                                blank=True,
                                null=True)
    description = models.TextField()

    def __str__(self):
        return self.name

    def image_tag(self):
        return mark_safe('<img src="{}" width="150" height="150" />'.format(self.image.url))

    image_tag.short_description = 'Image'

    @classmethod
    def add_band(cls, band):

        # Add genres before insert band
        try:
            cls.objects.create(
                name=band['name'],
                popularity=band['popularity'],
                description=band['description'],
                image=band['image'],
            )
            for genre in band['genre']:
                BandGenres.add_genre(band['name'], genre)
        except Exception as e:
            print(f'Band {band["name"]} was not added {e}')


class BandGenres(models.Model):
    band = models.ForeignKey(Band, unique=False)
    genre = models.ForeignKey(Genres)

    @classmethod
    def add_genre(cls, band: str, genre: str):
        try:
            Genres.add_genre(genre)
        except:
            pass
        cls.objects.create(
            band=Band.objects.get(name=band),
            genre=Genres.objects.get(name=genre)
        )


class Album(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to=update_filename)
    band = models.ForeignKey(Band, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def image_tag(self):
        return mark_safe('<img src="{}" width="150" height="150" />'.format(self.image.url))

    image_tag.short_description = 'Image'

    @classmethod
    def add_album(cls, album):
        # try:
        cls.objects.create(
            name=album['name'],
            image=album['image'],
            band=Band.objects.get(name=album['band']),
        )
        # except:
        #     print(f'Album {album["name"]} was not added')


class Song(models.Model):
    name = models.CharField(max_length=100)
    genre = models.ForeignKey(Genres,
                              models.SET_NULL,
                              blank=True,
                              null=True)
    duration = models.IntegerField(blank=True, null=True)
    lyrics = models.TextField(default='No lyrics')
    song_file = models.FileField(upload_to=update_filename)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    band = models.ForeignKey(Band, on_delete=models.CASCADE)
    # img_url = models.ImageField(upload_to=update_filename)
    popularity = models.FloatField(blank=True, null=True)
    vote_average = models.FloatField(blank=True, null=True)
    vote_count = models.FloatField(blank=True, null=True)
    song_status = models.ForeignKey(Status,
                                    models.SET_NULL,
                                    blank=True,
                                    null=True)

    def __str__(self):
        return self.name

    @classmethod
    def add_song(cls, song, song_file):
        try:
            with open(song_file, 'rb') as f:
                cls.objects.create(
                    name=song['name'],
                    genre=Genres.objects.get(name=song['genre']),  # new field
                    duration=song['duration'],
                    lyrics=song['lyrics'],
                    song_file=File(f),
                    album=Album.objects.get(name=song['album']),
                    band=Band.objects.get(name=song['band']),
                    img_url=song['img_url'],  # new field
                    popularity=song['popularity'],  # new field
                    vote_average=song['vote_average'],  # new field
                    vote_count=song['vote_count'],  # new field
                    song_status=song['song_status'],  # new field
                )
        except:
            print(f'Song {song["name"]} was not added')

    def song_tag(self):
        return mark_safe('<audio controls><source src="{}"/></audio>'.format(self.song_file.url))

    song_tag.short_description = 'Song'


class LikedByUsers(models.Model):
    user = models.ForeignKey(User, unique=False)
    band = models.ForeignKey(Band, null=True)

music/forms.py
from django import forms
from django.contrib.auth.models import User


# Registration user form
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


# Log in user form
class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput(render_value=False), max_length=100)

music/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.utils import IntegrityError
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views import generic

from .forms import UserForm, LoginForm
from .models import Band, Album, LikedByUsers, BandGenres


class BandView(generic.DetailView):
    queryset = Band.objects.all()
    template_name = 'music/BandView.html'
    context_object_name = 'band'


class AlbumView(generic.DetailView):
    queryset = Album.objects.all()
    template_name = 'music/AlbumView.html'
    context_object_name = 'album'


class BandListView(generic.ListView):
    model = Band
    template_name = 'music/BandListView.html'
    context_object_name = 'bands'
    paginate_by = 30
    ordering = ['-popularity']


class AlbumListView(generic.ListView):
    model = Album
    template_name = 'music/AlbumListView.html'
    context_object_name = 'albums'

    def get_queryset(self):
        if 'pk' in self.kwargs.keys():
            band = get_object_or_404(Band, pk=self.kwargs['pk'])
            return Album.objects.filter(band=band)
        return Album.objects.all()


def index(request):
    form = UserForm(request.POST or None)
    bands = Band.objects.all().order_by('?')[:12]
    context = {
        'bands': bands,
        'form': form
    }
    return render(request, 'music/index.html', context)


def bands_list(request):
    bands = Band.objects.all().order_by('?')
    context = {
        'bands': bands,
    }
    return render(request, 'music/BandListView.html', context)


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect(reverse('music:account'))
    return render(request, 'music/user/registration.html', {'form': form})


def login_user(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect(reverse('music:account'))
            else:
                context = {'error_message': 'Your account has been blocked', 'form': form}
                return render(request, 'music/user/login.html', context)
        else:
            context = {'error_message': 'Incorrect login or password', 'form': form}
            return render(request, 'music/user/login.html', context)
    return render(request, 'music/user/login.html', {'form': form})


# Logout user and redirect to main page
def logout_user(request):
    if request.user.is_authenticated():
        logout(request)
    return redirect(reverse('music:index'))


@login_required
def liked_bands(request):
    try:
        LikedByUsers.objects.create(
            user=request.user,
            band=Band.objects.get(pk=request.POST['band_id'])
        ).save()
    except IntegrityError:
        print('already exists')

    return redirect(reverse('music:bands'))


@login_required
def disliked_bands(request):
    LikedByUsers.objects.filter(
        user=request.user,
        band=Band.objects.get(pk=request.POST['band_id']),
    ).delete()
    return redirect(reverse('music:bands'))


@login_required
def liked(request):
    liked_bands = LikedByUsers.objects.filter(user=request.user).values_list('band', flat=True)
    bands = Band.objects.filter(id__in=liked_bands)
    context = {
        'bands': bands,
    }
    return render(request, 'music/user/liked.html', context=context)


@login_required
def recommendations(request):
    liked_bands = LikedByUsers.objects.filter(user=request.user).values_list('band', flat=True)
    bands = Band.objects.filter(id__in=liked_bands)

    liked_genres = []
    for liked in liked_bands:
        result = BandGenres.objects.filter(band=liked).values_list('genre', flat=True)
        liked_genres += result
    liked_genres = set(liked_genres)

    rank = []
    bands_id = Band.objects.all().values_list('id', flat=True)
    for band_id in bands_id:
        genres = BandGenres.objects.filter(band=band_id).values_list('genre', flat=True)
        rank.append((band_id, len(set(genres).intersection(liked_genres))))

    rank.sort(key=lambda x: x[1], reverse=True)
    ids = [x[0] for x in rank][:30]
    bands = Band.objects.filter(id__in=ids)

    return render(request, 'music/user/recommendations.html', context={'bands': bands})


# User information page
@login_required
def user_account(request):
    if not request.user.is_authenticated():
        return redirect(reverse('music:register'))
    else:
        context = {
            'username': request.user.username,
        }

        return render(request, 'music/user/account.html', context=context)


def search_band(request):
    results = None
    if request.method == 'POST' and request.POST['search_text']:
        search_text = request.POST['search_text']
        results = Band.objects.filter(name__contains=search_text)[:6:-1]

    return render(request, 'music/ajax_search.html', {'bands': results})

music/templates/music/AlbumView.html
{% extends 'music/base.html' %}
{% load static %}
{% load app_filters %}

{% block title %} {{ album.name }} by {{ album.band.name }}{% endblock %}

{% block css_files %}
<link rel="stylesheet" type="text/css" href="{% static 'music/Album_view.css' %}">

{% endblock %}

{% block body %}

     <div id="topSurface">

        <div class="container" id="topPart1">
            {% with image_path=album.image.url|check %}
                {% if image_path %}
                    <img class="img-thumbnail" id="topPartPic" src="{% static image_path %}" alt="{{ album.name }}"/>
                {% else %}
                    <img class="img-thumbnail" id="topPartPic" src="{% static 'music/image_for_site/noimage.jpg' %}"/>
                {% endif %}
            {% endwith %}
        </div>


        <div class="container" id="topPart2">
            <h1>{{ album.name }}</h1>
            <h3>by {{ album.band.name }}</h3>
        </div>

    </div>

    <div id="sect">
        <h1>Songs</h1>
        <div id="intermediate"></div>
    </div>

    <div id="subsect">
            <div id="inner">
                {% for song in album.song_set.all %}
                    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
                    {% if forloop.counter  %}
                    <div class="container" id="part1">
                        <h4>{{ forloop.counter }}. {{ song.name|truncatewords:6 }}</h4>
                         <div id="intermediate2"></div>
                        <br>
                        {% with music_path=song.song_file.url|music_check %}
                            <audio controls>
                                <source src="{% static music_path %}" type="audio/mp3">
                            </audio>
                        {% endwith %}
                        <br><br>
                        <div id="intermediate2"></div>
                        <br>
                    </div>
                    {% endif %}
                    </div>
                {% endfor %}
            </div>
        <br><br>
    </div>



{% endblock %}

music/templates/music/BandView.html
{% extends 'music/base.html' %}

{% block title %}{{ band.name }} band{% endblock %}

{% load static %}
{% load app_filters %}

{% block css_files %}
    <link rel="stylesheet" type="text/css" href="{% static 'music/BandView.css' %}">
{% endblock %}


{% block body %}

    <div id="topSurface">

        <div class="container" id="topPart1">
            {% with image_path=band.image.url|check %}
                {% if image_path %}
                    <img class="img-thumbnail" id="topPartPic" src="{% static image_path %}" alt="{{ band.name }}"/>
                {% else %}
                    <img class="img-thumbnail" id="topPartPic" src="{% static 'music/image_for_site/noimage.jpg' %}" />
                {% endif %}
            {% endwith %}
        </div>


        <div class="container" id="topPart2">
            <h1>{{ band.name }}</h1>
            <p>{{ band.description|truncatewords:100 }}</p>
        </div>

    </div>
    <div id="sect">
        <h1>Albums({{ band.album_set.all.count }})</h1>
        <div id="intermediate"></div>
    </div>


    <div class="container" id="albumView">
        <div class="row">
            {% for album in band.album_set.all %}
                <article class="col-xs-12 col-sm-5 col-md-4 col-lg-4">
                        <div class="panel panel-default">
                            <div class="panel-body">

                                <a href="{% url 'music:album' album.pk %}" title="{{ album.name }}" class="zoom" data-title="Albums" data-type="image" data-toggle="lightbox">
                                    {% with image_path=album.image.url|check %}
                                        {% if image_path %}
                                            <img src="{% static image_path %}" alt="{{ album.name }}" id="itemGallery"/>
                                        {% else %}
                                            <img src="{% static 'music/image_for_site/noimage.jpg' %} " id="itemGallery"/>
                                        {% endif %}
                                    {% endwith %}
                                </a>

                            </div>
                            <div class="panel-footer">
                                <h4><a href="{% url 'music:album' album.pk %}" title="{{ album.name }}"><strong style="color: black">{{ album.name|truncatewords:5 }}</strong></a></h4>
                                <h5><a href="#" style="color: darkgray">{{ band.name }}</a></h5>
                                <span class="pull-right">
                                    <i id="like1" class="glyphicon glyphicon-thumbs-up"></i>
                                    <i id="like1-bs3"></i>
                                    <i id="dislike1" class="glyphicon glyphicon-thumbs-down"></i>
                                    <i id="dislike1-bs3"></i>
                                </span>
                            </div>
                        </div>
                </article>
            {% endfor %}
        </div>
    </div>





{% endblock %}

music/templates/music/ajax_search.html
{% load static %}
{% load app_filters %}
{% block css_files %}
    <link rel="stylesheet" type="text/css" href="{% static 'music/ajax_search.css' %}">
{% endblock %}
<script src="{% static 'music/js/liked_by_users.js' %}"></script>
{% if bands %}
    <div id="items">
        {% for band in bands %}
                <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5">
                        <div id="item">
                                <a href="{% url 'music:band' band.pk %}"
                                   title="{{ band.name }}"
                                   class="zoom"
                                   data-title="Bands"
                                   data-type="image"
                                   data-toggle="lightbox">
                                    {% with image_path=band.image.url|check %}
                                        {% if image_path %}
                                            <img src="{% static image_path %}" alt="{{ band.name }}" id="itemGallery"/>
                                            <a class="like fa fa-thumbs-o-up" data-value="{{ band.pk }}"></a>
                                            <a class="dislike fa fa-thumbs-o-down" data-value="{{ band.pk }}"></a>
                                        {% else %}
                                            <img src="{% static 'music/image_for_site/noimage.jpg' %}" />
                                        {% endif %}
                                    {% endwith %}
                                    <h3>{{ band.name }}</h3>
                                </a>
                        </div>
                </div>
        {% endfor %}
    </div>
{% else %}
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div id="no_result">
            <h4>No suggestions</h4>
        </div>
    </div>
{% endif %}

music/templates/music/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="Keywords" content="MusicLoft">
        <meta name="description" content="Content of music">

        <title>
            {% block title %}MusicHub - everywhere you want{% endblock %}
        </title>

        {% load static %}

        <link rel="stylesheet" type='text/css' href="{% static 'music/bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'music/bower_components/bootstrap-social/bootstrap-social.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'music/bower_components/font-awesome/css/font-awesome.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'music/user/band_view_likes.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'music/base.css' %}">
        {% block css_files %}{% endblock %}

        <div>
            <nav class="navbar navbar-fixed-top" id="nav-main">

            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mynavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>

              <svg xmlns="http://www.w3.org/2000/svg" class="equilizer" viewBox="0 0 128 128">
                      <g>
                          <title>Audio Equilizer</title>
                          <rect class="bar" transform="translate(0,0)" y="15"></rect>
                          <rect class="bar" transform="translate(25,0)" y="15"></rect>
                          <rect class="bar" transform="translate(50,0)" y="15"></rect>
                          <rect class="bar" transform="translate(75,0)" y="15"></rect>
                          <rect class="bar" transform="translate(100,0)" y="15"></rect>
                      </g>
              </svg>
              <a class="navbar-brand" href="{% url 'music:index' %}" id="Brnd">
                  <strong>
                      <ul class="letters">
                      <!--MUSICLOFT-->
                          <li>M</li>
                          <li>U</li>
                          <li>S</li>
                          <li>I</li>
                          <li>C</li>
                          <li>L</li>
                          <li>O</li>
                          <li>F</li>
                          <li>T</li>
                      </ul>
                  </strong></a>
            </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="mynavbar">
              <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle"  data-toggle="dropdown" id="BndBar"><strong>BANDS </strong></a>
                    <ul class="dropdown-menu" role="menu" style="background-color: white">
                        {% for band in bands %}
                            {% if forloop.counter < 5 %}
                                <li><a href="{% url 'music:band' band.pk %}">{{ band.name }}</a></li>
                            {% endif %}
                        {% endfor %}
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'music:bands' %}" style="text-align: center"><strong>All bands</strong></a></li>
                    </ul>
                </li>

                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="EventBar"><strong>EVENTS </strong></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">One more separated link</a></li>
                  </ul>
                </li>
              </ul>


              <ul class="nav navbar-nav navbar-right">
                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'music:register' %}" id="JoinBar"><strong>JOIN </strong></a></li>
                    <li><a href="{% url 'music:login' %}" id="LogBar"><strong>LOGIN </strong></a></li>
                    <li><a href="#" id="Question" style="font-size: 20px; color: white; "><strong>?</strong></a></li>
                {% else %}
                   <li class="dropdown">
                        <a href="#" id="Logged" class="dropdown-toggle" data-toggle="dropdown">
                            <strong>WELCOME {{ request.user.username }}<b class="caret"></b></strong>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'music:liked' %}"><i class="icon-cog"></i> Liked bands</a></li>
                            <li><a href="{% url 'music:recommendations' %}"><i class="icon-cog"></i> Recommendations</a></li>
                            <li><a href="#"><i class="icon-envelope"></i> Contact Support</a></li>
                            <li class="divider"></li>
                            <li><a href="{% url 'music:logout' %}"><i class="icon-off"></i> Logout</a></li>
                        </ul>
                   </li>
                {% endif %}
              </ul>
                <div class="container">
                    <div class="col-sm-3 col-md-3">
                        <form class="navbar-form" id="search_above" role="search" method="get" action="{% url 'music:index' %}">
                            <div class="input-group" id="search_id">
                                <input type="text" class="form-control" id="search" name="q" value="" placeholder="Search">
                                {% csrf_token %}
                                <div class="input-group-btn">
                                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div id="search_results"></div>
                </div>
            </div><!-- /.navbar-collapse -->
        </nav>
        </div>
    </head>
    <body>
        <script src="{% static 'music/bower_components/jquery/dist/jquery.min.js' %}"></script>
        {% block body %}{% endblock %}
        <div class="footer" style="background: linear-gradient(dimgrey, #000000)">
            <div class="container">
                <br><br>
                <button style="width: 100%; margin-left: auto; margin-right: auto;  color: whitesmoke; font-family: Roboto, sans-serif; font-size: 20px; "  type="button" class="navbar-toggle" data-toggle="collapse" data-target="#footer-middle">
                    <strong><i class="glyphicon glyphicon-chevron-down"></i></strong>
                </button>

                <div class="row collapse navbar-collapse" id="footer-middle">
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" id="first">
                        <ul style="list-style-type:none">
                            <li>PRODUCT</li>
                            <li><br></li>
                            <li>Business</li>
                            <li>Compare</li>
                            <li>Features</li>
                            <li>Pricing</li>
                            <li>Mobile</li>
                            <li>App Showcase</li>
                            <li>Download</li>
                        </ul>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" id="second">
                        <ul style="list-style-type:none">
                            <li>COMPANY</li>
                            <li><br></li>
                            <li>About Us</li>
                            <li>Blog</li>
                            <li>News</li>
                            <li>Press Releases</li>
                            <li>Jobs</li>
                            <li>Contact Us</li>
                        </ul>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" id="third">
                        <ul style="list-style-type:none">
                            <li>LEARN MORE</li>
                            <li><br></li>
                            <li>Support</li>
                            <li>Developers</li>
                            <li>Referral</li>
                            <li>Affillate</li>
                            <li>Reseller</li>
                            <li>Folder Sharing FAQ</li>
                        </ul>
                    </div>
                </div>
                <br><br>
                <div id="social_media">
                    <button class="btn btn-social-icon btn-lg btn-facebook">
                      <span class="fa fa-facebook"></span>
                    </button>
                    <button class="btn btn-social-icon btn-lg btn-linkedin">
                      <span class="fa fa-linkedin"></span>
                    </button>
                    <button class="btn btn-social-icon btn-lg btn-twitter">
                      <span class="fa fa-twitter"></span>
                    </button>
                    <button class="btn btn-social-icon btn-lg btn-instagram">
                      <span class="fa fa-instagram"></span>
                    </button>
                    <button class="btn btn-social-icon btn-lg btn-google">
                      <span class="fa fa-google"></span>
                    </button>
                    <button class="btn btn-social-icon btn-lg btn-youtube">
                      <span class="fa fa-youtube"></span>
                    </button>
                </div>
                <br><br>

                <div class="row" id="footer-intermediate"></div>

                <div id="footer-end">
                    <h6>&copy 2016 MusicLoft, Inc. All Rights Reserved.</h6>
                    <h5>Terms of Service * Privacy Policy * Site Map.</h5>
                </div>
                <br><br><br><br>
            </div>
        </div>
        <script src="{% static 'music/bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'music/js/carousel.js' %}"></script>
        <script src="{% static 'music/js/ajax_search.js' %}"></script>
        <script src="{% static 'music/js/player.js' %}"></script>
        <script src="{% static 'music/js/liked_by_users.js' %}"></script>
    </body>
</html>